services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.linux
    container_name: python-ui-scripting-crawler
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /local/home/rbadmin_app1/mount/crawer/config:/app/config
      - /local/home/rbadmin_app1/mount/crawer/input:/app/input
      - /local/home/rbadmin_app1/mount/crawer/input_done:/app/input_done
      - /local/home/rbadmin_app1/mount/crawer/output:/app/output
      - /local/home/rbadmin_app1/mount/crawer/log:/app/log
    command: ["python", "-m", "src.main", "--watch-input", "--headless"]
